name: VALIDATOR
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - "*"
jobs:
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Start checks
        run: echo Starting...
      # Runs a set of commands using the runners shell
      - name: Run Validate Mysql schema seed data
        run: /bin/bash validator/mysql-validator.sh
      # Runs basic syntax validation on yaml files in alerts folder

