name: VALIDATOR
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - "*"
jobs:
  mySQLValidator:
    #finds the changed files and if there are changes in schema/seed-data directory then it executes those queries on test database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Changed-files
        # Gets the changed files using the sha and calls the process-files.sh by passing the list of changed files
        id: changedFiles
        run: |
          all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          /bin/bash validations/process-files.sh "${all}"
      - name: DB Execution
        #If changes are in schema/seed-data then queries will be executed using mysql-execution script
        run: |
           if ( ${{steps.changedFiles.outputs.isDBFileChangeExists}} ); then
             /bin/bash validations/mysql-execution.sh "${{steps.changedFiles.outputs.schema}}" "${{steps.changedFiles.outputs.seedData}}"
           fi

