name: VALIDATOR
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - "*"
jobs:
  validate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      # Runs a single command using the runners shell
      - name: Start checks
        run: echo Starting...
      # Runs a set of commands using the runners shell
      - name: Install dependecies
        run: |
          sudo apt-get -y install python3-pip
          python -m pip install --upgrade pip jsonschema
      - name: Validate Json
        run: python validations/validationscript.py .



