name: VALIDATOR
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - "*"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.arrayId.outputs.array }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: find the git diff files
        id: arrayId
        run: |
          all=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          /bin/bash validations/validator.sh "${all}"

      - name: Change the src permissions
        run: chmod -R +x src/*
      - name: run the db
        run: |
           if [[ ${{steps.arrayId.outputs.isDBFileChangeExists}} ]]; then
             /bin/bash validations/dbExecution.sh "${{steps.arrayId.outputs.schema}}" "${{steps.arrayId.outputs.seedData}}"
           fi
           

