name: VALIDATOR
on:
  push:
    branches:
      - "*"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Run bash script
        shell: bash
        run: |
          chmod +x ./src
          bindu='GitHub'
          ./src/resources/test.sh "${bindu}"